/*Consultando dados nas tabelas*/

SELECT [NOME], [CPF], [ESTADO]
FROM [TABELA DE CLIENTES];


SELECT [NOME] AS [NOME DO CLIENTE] , [CPF], [ESTADO] AS [UF]
FROM [TABELA DE CLIENTES];


SELECT * FROM [TABELA DE PRODUTOS];

SELECT * FROM [TABELA DE CLIENTES];


SELECT [NOME],[ESTADO] FROM [TABELA DE CLIENTES];

SELECT [ESTADO],[NOME] FROM [TABELA DE CLIENTES];

/*Colocando dados em ordenação*/
SELECT [NOME],[ESTADO] FROM [TABELA DE CLIENTES]
ORDER BY [NOME];